// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hovvwniyxnzskocsmgcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvdnZ3bml5eG56c2tvY3NtZ2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzNDI0ODAsImV4cCI6MjA4NzkxODQ4MH0.XzciHb-ysEx25cc4HHqLT8VcUr_0JuOGv8I3rZAronw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});